import { CalendarEvent } from './types';

export const INITIAL_EVENTS: CalendarEvent[] = [
  // --- FERIADOS NACIONAIS 2026 ---
  {
    id: 'f-nac-1',
    title: 'Ano Novo (Confraternização Universal)',
    description: 'Primeiro dia do ano, feriado nacional de renovação e celebração.',
    date: '2026-01-01',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-2',
    title: 'Carnaval (Terça-Feira)',
    description: 'Festividade tradicional e cultural brasileira.',
    date: '2026-02-17',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-3',
    title: 'Quarta-feira de Cinzas',
    description: 'Início do período da Quaresma do calendário litúrgico (ponto facultativo até às 14h).',
    date: '2026-02-18',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-4',
    title: 'Sexta-feira Santa (Sexta da Paixão)',
    description: 'Celebração religiosa nacional cristã que marca a Paixão de Cristo.',
    date: '2026-04-03',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-5',
    title: 'Tiradentes',
    description: 'Homenagem a Joaquim José da Silva Xavier (Tiradentes), mártir da Inconfidência Mineira.',
    date: '2026-04-21',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-6',
    title: 'Dia do Trabalhador',
    description: 'Celebração mundial do Dia Internacional dos Trabalhadores.',
    date: '2026-05-01',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-7',
    title: 'Corpus Christi',
    description: 'Festividade litúrgica católica de Corpus Christi (ponto facultativo nacional).',
    date: '2026-06-04',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-8',
    title: 'Independência do Brasil',
    description: 'Comemoração da Declaração de Independência de 1822.',
    date: '2026-09-07',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-9',
    title: 'Nossa Senhora Aparecida',
    description: 'Padroeira oficial do Brasil.',
    date: '2026-10-12',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-10',
    title: 'Finados',
    description: 'Dia de homenagem e lembrança dos mortos.',
    date: '2026-11-02',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-11',
    title: 'Proclamação da República',
    description: 'Celebração da Proclamação da República Brasileira em 1889.',
    date: '2026-11-15',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-12',
    title: 'Dia Nacional de Zumbi e da Consciência Negra',
    description: 'Marco histórico de reflexão sobre a cultura afro-brasileira e igualdade social.',
    date: '2026-11-20',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },
  {
    id: 'f-nac-13',
    title: 'Natal',
    description: 'Celebração cristã do nascimento de Jesus Cristo.',
    date: '2026-12-25',
    category: 'feriado_nacional',
    location: 'Brasil inteiro',
    isSystemHoliday: true,
  },

  // --- FERIADOS MUNICIPAIS DE BELL HORIZONTE (BH) ---
  {
    id: 'f-bh-1',
    title: 'Assunção de Nossa Senhora',
    description: 'Feriado municipal em Belo Horizonte celebrando a Assunção de Maria.',
    date: '2026-08-15',
    category: 'feriado_bh',
    location: 'Belo Horizonte - MG',
    isSystemHoliday: true,
  },
  {
    id: 'f-bh-2',
    title: 'Imaculada Conceição (BH)',
    description: 'Feriado municipal de Belo Horizonte consagrado à Imaculada Conceição.',
    date: '2026-12-08',
    category: 'feriado_bh',
    location: 'Belo Horizonte - MG',
    isSystemHoliday: true,
  },

  // --- FERIADOS MUNICIPAIS DE SÃO PAULO (SP) ---
  {
    id: 'f-sp-1',
    title: 'Aniversário de São Paulo',
    description: 'Feriado municipal em comemoração à fundação da cidade de São Paulo em 1554.',
    date: '2026-01-25',
    category: 'feriado_sp',
    location: 'São Paulo - SP',
    isSystemHoliday: true,
  },
  {
    id: 'f-sp-2',
    title: 'Revolução Constitucionalista',
    description: 'Feriado estadual que reverencia os combatentes paulistas de 1932.',
    date: '2026-07-09',
    category: 'feriado_sp',
    location: 'São Paulo - SP',
    isSystemHoliday: true,
  },

  // --- CORPORATE / USER SAMPLE EVENTS ---
  // Q1
  {
    id: 'corp-1',
    title: 'Planejamento Estratégico Q1',
    description: 'Alinhamento geral de objetivos da diretoria e chefias de equipe para o início do ano.',
    date: '2026-01-08',
    time: '09:00',
    category: 'interno',
    location: 'Sala de Conferências Principal',
  },
  {
    id: 'corp-2',
    title: 'Demo Day & Pitch Comercial Tripla',
    description: 'Apresentação de propostas comerciais de alta velocidade para três parceiros do setor varejista.',
    date: '2026-02-12',
    time: '14:30',
    category: 'comercial_tripla',
    location: 'Auditorium SP & Zoom',
  },
  {
    id: 'corp-3',
    title: 'Campanha Integrada Patrocinada Samsung',
    description: 'Lançamento oficial das peças de marketing co-patrocinadas com a Samsung Mobile.',
    date: '2026-03-11',
    time: '11:00',
    category: 'comercial_patrocinado',
    location: 'Agência Digital & Meets',
  },
  // Q2
  {
    id: 'corp-4',
    title: 'Alinhamento Geral com Stakeholders',
    description: 'Sessão interna trimestral para comunicação de receitas operacionais brutas e metas cumpridas.',
    date: '2026-04-15',
    time: '10:00',
    category: 'interno',
    location: 'Microsoft Teams',
  },
  {
    id: 'corp-5',
    title: 'Lançamento Comercial Triplo - Upgrade Brasil',
    description: 'Campanha de escalonamento tecnológico para as três principais operadoras do país.',
    date: '2026-05-18',
    time: '16:00',
    category: 'comercial_tripla',
    location: 'BH Office - Sala VIP',
  },
  {
    id: 'corp-6',
    title: 'Fórum Patrocinado de Cloud & IA - AWS',
    description: 'Painel com lideranças de tecnologia patrocinado pela equipe corporativa AWS.',
    date: '2026-06-19',
    time: '14:00',
    category: 'comercial_patrocinado',
    location: 'Centro de Convenções Rebouças (SP)',
  },
  // Q3
  {
    id: 'corp-7',
    title: 'Hackathon Interno - Inovação 2026',
    description: 'Competição de 48h entre programadores e designers internos para incubação de novas ideias.',
    date: '2026-07-23',
    time: '09:00',
    category: 'interno',
    location: 'Espaço Maker & Discord',
  },
  {
    id: 'corp-8',
    title: 'Ação Tripla: Dia dos Pais Varejo',
    description: 'Execução de vendas conjuntas com três marcas de vestuário e autocuidado masculino.',
    date: '2026-08-05',
    time: '13:00',
    category: 'comercial_tripla',
    location: 'Stand SP Shopping',
  },
  {
    id: 'corp-9',
    title: 'Summit FinTech Patrocinado Nubank',
    description: 'Conferência voltada para inovações no mercado de pagamentos brasileiro com patrocínio Premium Purple.',
    date: '2026-09-22',
    time: '09:30',
    category: 'comercial_patrocinado',
    location: 'Auditório Principal SP / Online',
  },
  // Q4
  {
    id: 'corp-10',
    title: 'Revisão Anual de Desempenho (OKRs)',
    description: 'Assembleia com todos os colaboradores para fechamento das metas corporativas do ano.',
    date: '2026-12-10',
    time: '15:00',
    category: 'interno',
    location: 'Híbrido (BH Auditório + Zoom)',
  },
  {
    id: 'corp-11',
    title: 'Black Friday Comercial Tripla Especial',
    description: 'Lançamento sincronizado de descontos agressivos para canais de e-commerce e afiliados.',
    date: '2026-11-27',
    time: '00:01',
    category: 'comercial_tripla',
    location: 'Operação Central',
  },
  {
    id: 'corp-12',
    title: 'Workshop Cloud patrocinador Google AI Studio',
    description: 'Laboratório prático de IA patrocinado pela Google Cloud e equipes de developers brasileiras.',
    date: '2026-10-15',
    time: '14:00',
    category: 'comercial_patrocinado',
    location: 'Google Campus SP',
  },
];
